### ISSUE TITLE
Custom methods on server side for nested objects

### ISSUE THREAD

**Issue by kkrawczy** [spring-cloud/spring-cloud-contract#85]
It seems that that custom methods on the server side do not work when we use them to validate nested properties. 
To make it clear, let's consider a piece of a contract from http-server-dsl project:

``` groovy
body([
    fraudCheckStatus: "OK",
    rejectionReason : $(consumer(null), producer(execute('assertThatRejectionReasonIsNull($it)')))
])
```

And what if rejectionReason is an object with title, explanation, etc... and we want to check the title. If I change the contract to:

``` groovy
body([
    fraudCheckStatus: "OK",
    rejectionReason : [
        title: $(consumer(null), producer(execute('assertThatRejectionReasonIsNull($it)')))
    ]
])
```

the assert for "rejectionReason.title" is not generated (which also means that tests are passing).
BTW, I noticed this issue while working with spring-cloud-contract and with request objects that are a bit more complicated than the one in the example project.
Is this a known issue? Or maybe I structure the contract in a bad way?

**Comment by marcingrzejszczak** [comment]
That's interesting - most likely it's bug.

**Comment by marcingrzejszczak** [comment]
Done! Check out the snapshots - it should work

**Comment by kkrawczy** [comment]
This case works, thx.
Although a moment later I noticed that server side methods does not work with arrays.
So this contract:
```groovy
body([
    [
        rejectionReason: $(consumer(null), producer(execute('assertThatRejectionReasonIsNull($it)')))
    ],
    [
        rejectionReason: $(consumer(null), producer(execute('assertThatRejectionReasonIsNull($it)')))
    ]
])
```
will generate tests:
```java
DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
assertThatRejectionReasonIsNull(parsedJson.read("$.get(0).rejectionReason"));
assertThatRejectionReasonIsNull(parsedJson.read("$.get(1).rejectionReason"));
```
which will generate this error:
```java
com.jayway.jsonpath.InvalidPathException: Function with name: get does not exists.

	at com.jayway.jsonpath.internal.function.PathFunctionFactory.newFunction(PathFunctionFactory.java:70)
	at com.jayway.jsonpath.internal.path.FunctionPathToken.evaluate(FunctionPathToken.java:36)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:151)
	at org.springframework.cloud.contract.verifier.tests.FraudTest.validate_shouldMarkClientAsNotFraud(FraudTest.java:52)
```

I guess the problem is the jsonPath usage. It works fine with "$[0].rejectionReason" (I changed FraudDetectionController to return list)

I saw that there is already a task to enhance arrays handling in a response body, so I will let you move this issue there or create a new task for that.
Thx!

**Comment by marcingrzejszczak** [comment]
Check out the assertion of JSON size - https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_limitations . It should work. I think ;)

**Comment by kkrawczy** [comment]
I guess you mean "assertJsonSize" property. Though as far as I can see it will just generate additional assertion for collection size. The previous problems remains the same.
I added a patch, with changes I did in the http-server example.

[verifier_arrays-examle.txt](https://github.com/spring-cloud/spring-cloud-contract/files/522398/verifier_arrays-examle.txt)

**Comment by marcingrzejszczak** [comment]
Yeah actually I didn't manage to replicate this cause when you add that property the assertion is generated properly

**Comment by kkrawczy** [comment]
hmm, ok. I set to true assertJsonSize property in pom.xml and spring.cloud.contract.verifier.assert.size in application.yml and I still have an error. There is something that I missed?
I attached once again the patch. Can you just apply it and run clean install on http-server ? thx
[diff.txt](https://github.com/spring-cloud/spring-cloud-contract/files/522521/diff.txt)

**Comment by marcingrzejszczak** [comment]
Can you set up a sample app so that I can ensure that we're doing the same? It will be easier for me to debug this

**Comment by kkrawczy** [comment]
Hey, but the patch that I sent should be sufficient for that. Basically I cloned spring-cloud-contract and modified your sample app (spring-cloud-contract/samples/standalone/dsl/http-server) and made a patch with my changes that show the problem. So you could apply it on master and run/debug http-server app.
Sorry if this wasn't clear.

Otherwise you can just download this app. I made it based on http-server.
[example-app.zip](https://github.com/spring-cloud/spring-cloud-contract/files/527790/example-app.zip)


I will remind the problem (I will use snippets from my example app). For contract:
```groovy
response {
  status 200
  body([
    [
      name: $(consumer("userName 1"), producer(execute('assertThatUserNameIsNotNull($it)')))
    ],
    [
      name: $(consumer("userName 2"), producer(execute('assertThatUserNameIsNotNull($it)')))
    ]
  ])
}
```
The following test will be generated:
```java
// then:
assertThat(response.statusCode()).isEqualTo(200);
// and:
DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
assertThatJson(parsedJson).hasSize(2);
assertThatUserNameIsNotNull(parsedJson.read("$.get(0).name"));
assertThatUserNameIsNotNull(parsedJson.read("$.get(1).name"));
```
During test execution 
```java
response.getBody().asString() 
```
is equal to
```json
[{"id":1,"name":"Mike"},{"id":2,"name":"John"}]
```
so the data in the test is provided correctly. 
The problem is this expression
```java
parsedJson.read("$.get(0).name")
```
While evaluating this expression I get:
```java
com.jayway.jsonpath.InvalidPathException: Function with name: get does not exists.
        at com.jayway.jsonpath.internal.function.PathFunctionFactory.newFunction(PathFunctionFactory.java:70)
        at com.jayway.jsonpath.internal.path.FunctionPathToken.evaluate(FunctionPathToken.java:36)
        at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
        at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
        at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
        at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:151)
        at org.springframework.cloud.contract.verifier.tests.FraudTest.validate_shouldReturnListOfTheUsers(FraudTest.java:30)
```
But If I change `$.get(0).name` to `$[0].name` the test works fine.

That is why I believe that you might generate this jsonPath incorrectly.

Once again thx for checking that.

**Comment by marcingrzejszczak** [comment]
Yeah I didn't get what you were saying but now I do, thx. Will try to check it out asap

**Comment by marcingrzejszczak** [comment]
Hopefully this time it will work ;) Sorry that you had to wait for so long! @kkrawczy

**Comment by kkrawczy** [comment]
Thx for the fix! :)
